# ~/.config/InPostReturnLabel/config.yaml
---
default_mode: "ipp"  # "cups" or "ipp" or "preview"
printer:
  cups:
    printer_name: "Brother_QL_1110NWB"
  ipp:
    printer_uri: "ipp://192.168.1.2:631/ipp/print"
    check_media: "om_brother-label-103x164mm_103x164mm"
    dpi: 300
template:
  font_path: null

server:
  debug: false
  port: 8090
  bind_address: "0.0.0.0"
